version: "3.9"
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - ffc

  ffc-experiments-k8s:
    build:
      context: ../FeatureFlagsCo.Experiments
      args:
        exptenv: k8s
      dockerfile: Dockerfile.k8s
    image: ffc-experiments
    depends_on:
      - redis
    ports:
      - 80:80
    networks:
      - ffc
    # volumes:
    #   - ./log:/var/log/

networks:
  ffc:
    name: ffc-network
